### PR TITLE
Passing client to chansend and lazy version

### PR DESCRIPTION
**Pull request by Krukov**

### CODE REVIEW

**Comment by andrewgodwin** [comment]
Why the lazy version?

**Comment by Krukov** [comment]
Lazy version because when you use this package as source (by adding package path to the `PYTHONPATH`), importing this package got error with message ```pkg_resources.DistributionNotFound: The 'asgi_redis' distribution was not found and is required by the application``` (I think that is because module didn't install with pip) 
Full traceback
```python
>>> import asgi_redis
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "asgi_redis/__init__.py", line 7, in <module>
    version = pkg_resources.require('asgi_redis')[0].version
  File "/home/frog/.virtualenvs/test2/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/frog/.virtualenvs/test2/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 854, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'asgi_redis' distribution was not found and is required by the application

```

**Comment by andrewgodwin** [comment]
Ah, right. I'd suggest instead then that the version string is moved into the module and we import the module in setup.py like the other packages; it was only done like this before because it was a single module. I'd like to keep it as `__version__`.

**Comment by Krukov** [comment]
Oh. I did it by by other way. Does  it matter?

**Comment by andrewgodwin** [comment]
No, this seems fine, I've done the same before in other packages.

**Pull request merged**
