### PR TITLE
Proposed fix for #44

### LINKED ISSUE #44: RedisChannelLayer.receive runs forever
`RedisChannelLayer.receive`, that was reworked in #43, now hangs forever if called with block. That was not the case in the previous version (it returned `(None, None)`. This prevents channels `Worker` from exiting if termed is set to true (e.g. in the signal handler).

### PR DESCRIPTION
**Pull request by AlexejStukov**
This should fix #44. Hope it does not break anything else.

### CODE REVIEW

**Comment by proofit404** [comment]
Hi,

Thanks for your contribution. Tests to prove that problem was present and solved wold be greet.

**Comment by AlexejStukov** [comment]
Travis build hangs as expected

**Comment by AlexejStukov** [comment]
This one should complete.

**Comment by AlexejStukov** [comment]
Is it OK now, @proofit404?

**Comment by andrewgodwin** [comment]
Rejecting this - see my response to #44.

**Comment by proofit404** [comment]
Actually, the whole point of `block=True` argument is to wait until the message is available.

**Pull request closed without merging**
